
//Auto generated by tgf util
//created at 2023-06-12 17:17:01.9016842 +0800 CST m=+0.028897001

using AOT;

namespace HotFix.Code
{
    public struct ServerApi
    {
	
 		public static readonly Api Login = new("login","Login");
	
	}
	
}
